INSERT INTO rol (rol_nombre) VALUES ('ROLE_ADMIN'), ('ROLE_USER'), ('ROLE_SECRETARIA');

INSERT INTO public.usuario(apellido, email, nombre, nombre_usuario, password, rut) VALUES ('admin', 'a@a.a','admin' ,'admin' , '$2a$10$g1NiG2AiQpTxg/a8HkvB.ObqopcO1QCk76jywtelrv17BMpulR4F2', '123456');
	
INSERT INTO public.usuario(apellido, email, nombre, nombre_usuario, password, rut) VALUES ('user', 's@s.s', 'user', 'user', '$2a$10$H7JVREJUNernaPQ7ruDbpeWjXqv.K2a0oninIjJJzAL3sFWfEGw3O', '1234569');
	
INSERT INTO public.usuario(apellido, email, nombre, nombre_usuario, password, rut) VALUES ('trabajador', 'u@u.u', 'trabajador', 'trabajador','$2a$10$GrxgW1ydycwaoNGdMWrykulnU8w90ay2oS/p4G60mkMx3hbJRlNfC', '98765432');

INSERT INTO public.usuario_rol(	usuario_id, rol_id)	VALUES (1, 1);
INSERT INTO public.usuario_rol(	usuario_id, rol_id)	VALUES (2, 3);
INSERT INTO public.usuario_rol(	usuario_id, rol_id)	VALUES (3, 2);


INSERT INTO public.plato(calorias, detalle, estado,foto,miseplace ,nombre, observaciones, preparacion, punto_critico)VALUES ( 120,'ARROZ CON LECHE','activo','0dccfe2b-d443-422c-bd83-fdb0d566ccf5_arroz_con_leche_800x800.webp','Sanitizar empaque primario de arroz, leche, azúcar, canela y esencia.' ,'ARROZ CON LECHE','OBSERVACIONES', 'Poner en una olla 150 cc de agua y llevar a ebullición. Agregar el arroz con leche, dejar cocinar durante 20 a 25 minutos sin dejar de revolver, ya cocinado el arroz, apagar fuego y dejar que baje la temperatura.Una vez templado, porciona en pocillos desechables y agrega coco rallado en el centro. ', 'PUNTOS CRÍTICOS *Controlar tiempo de cocción de preparación.*Montar en porciones individuales, esperar reducción de temperatura y mover a equipo de frio. ');
INSERT INTO public.plato(calorias, detalle, estado,foto,miseplace ,nombre, observaciones, preparacion, punto_critico)VALUES ( 450,'BIFE DE VACUNO CON ENSALADA ','activo','e2b0d297-6bac-4cda-ae1e-19f5e54edb3d_bife-con-ensalada-riquisima-foto-principal.jpg','Sanitizar verduras y envases primarios.Cortar vegetales (betarraga,lechuga y repollo) en juliana y chiffonade. Retirar exceso de tallos en brócoli y coliflor. Cortar vacuno en porciones tipo bife.' ,'REGIMEN HIPOCALÓRICO ','En montaje de platos asegurar que verduras cocidas tengan una temperatura menor a 5°C.En el caso del bife, montaje rápido en contenedores isotérmicos para no perder temperatura, utilizar horno mantenedor en caso de ser necesario. (T°>65°C).', 'En una olla blanquear, con una pizca de sal, durante 5 minutos el brócoli, coliflor y mix primavera, luego de transcurrido el tiempo enfriar con agua corriendo. En un sartén con aceite se incorpora el corte de vacuno con condimentos y sellar 5 minutos por lado, verificar temperatura interna (>65°C). Montar contenedor con cama de lechuga y repollo, por un lado la betarraga, primavera y crucíferas. ', '*Cuidar cadenas de frio en proteínas, <5°c en proteína cruda. *Respetar tiempos de cocción de proteínas y controlar temperatura de cocción, >75°C en centro del alimento. *Contaminación cruzada en productos crudos/cocidos y vegetales/cárnicos, respetar colores de tablas de cortar.');
INSERT INTO public.plato(calorias, detalle, estado,foto,miseplace ,nombre, observaciones, preparacion, punto_critico)VALUES ( 35,'ENSALADA 3 COLORES N°1  ','activo','a6fb89ed-4f58-425b-b121-ff92b663d410_receta-de-vinagreta-ensalada-de-col-y-zanahoria.jpg','Sanitizar verduras y cortar en corte juliana (zanahoria y repollo) y rodajas (pepino). Refrigerar. ' ,'ENSALADA  ','Montaje debe ser rápido para no perder temperatura de verduras. ', 'Verificar que los cortes de las verduras cumplan con lo establecido, montar en contenedores isotérmicos y refrigerar inmediatamente.   ', '*Controlar tiempo de sanitizado según producto utilizado. *Utilizar tablas verdes para mise en place.  *Supervisar temperatura de área y de equipos de frio. ');


INSERT INTO public.plato(detalle,estado,nombre)VALUES ('blanco','activo','Arroz');
INSERT INTO public.plato(detalle,estado,nombre)VALUES ('con carne','activo','Fetuchini');
INSERT INTO public.plato(detalle,estado,nombre)VALUES ('asado','activo','Pollo');
INSERT INTO public.plato(detalle,estado,nombre)VALUES ('al plato','activo','Humita');
INSERT INTO public.plato(detalle,estado,nombre)VALUES ('al horno','activo','Pastel de papa');

INSERT INTO public.tipo(nombre)VALUES ('ACEITES DE OLIVA');
INSERT INTO public.tipo(nombre)VALUES ('ACEITES ESPECIALES');
INSERT INTO public.tipo(nombre)VALUES ('ACEITES VEGETALES');
INSERT INTO public.tipo(nombre)VALUES ('ACETOS BALSAMICOS');
INSERT INTO public.tipo(nombre)VALUES ('VINAGRES');
INSERT INTO public.tipo(nombre)VALUES ('ACEITUNAS');s
INSERT INTO public.tipo(nombre)VALUES ('ENCURTIDOS');
INSERT INTO public.tipo(nombre)VALUES ('ARROZ');
INSERT INTO public.tipo(nombre)VALUES ('AZUCAR Y ENDULZANTES');
INSERT INTO public.tipo(nombre)VALUES ('CEREALES');
INSERT INTO public.tipo(nombre)VALUES ('DULCES Y CHOCOLATES');
INSERT INTO public.tipo(nombre)VALUES ('HUEVOS');
INSERT INTO public.tipo(nombre)VALUES ('LEGUMBRES');
INSERT INTO public.tipo(nombre)VALUES ('MERMELADAS Y DULCES');
INSERT INTO public.tipo(nombre)VALUES ('MINI PORCIONES');
INSERT INTO public.tipo(nombre)VALUES ('OTROS');
INSERT INTO public.tipo(nombre)VALUES ('PASTAS');
INSERT INTO public.tipo(nombre)VALUES ('SOPAS Y CREMAS');
INSERT INTO public.tipo(nombre)VALUES ('SAL ');
INSERT INTO public.tipo(nombre)VALUES ('HELADOS');
INSERT INTO public.tipo(nombre)VALUES ('TORTILLAS DE MAIZ');
INSERT INTO public.tipo(nombre)VALUES ('PAPAS BASTON');
INSERT INTO public.tipo(nombre)VALUES ('PASTAS');
INSERT INTO public.tipo(nombre)VALUES ('FRUTAS');
INSERT INTO public.tipo(nombre)VALUES ('GUARNICIONES LISTAS');
INSERT INTO public.tipo(nombre)VALUES ('JUGOS Y PULPAS');
INSERT INTO public.tipo(nombre)VALUES ('MEZCLAS ESPECIALES');
INSERT INTO public.tipo(nombre)VALUES ('VERDURAS');
INSERT INTO public.tipo(nombre)VALUES ('TOCINOS');
INSERT INTO public.tipo(nombre)VALUES ('FRUTAS');
INSERT INTO public.tipo(nombre)VALUES ('VERDURAS');
INSERT INTO public.tipo(nombre)VALUES ('	LOMO	');
INSERT INTO public.tipo(nombre)VALUES ('	PORCIONADOS	');
INSERT INTO public.tipo(nombre)VALUES ('	PULPAS	');
INSERT INTO public.tipo(nombre)VALUES ('	ELABORADOS CERDO	');
INSERT INTO public.tipo(nombre)VALUES ('	ELABORADOS POLLO	');
INSERT INTO public.tipo(nombre)VALUES ('	ELABORADOS VACUNO	');
INSERT INTO public.tipo(nombre)VALUES ('	HAMBURGUESAS CERTIFICADAS	');
INSERT INTO public.tipo(nombre)VALUES ('	HAMBURGUESAS PREMIUM	');
INSERT INTO public.tipo(nombre)VALUES ('	CARNES CERTIFICADAS	');
INSERT INTO public.tipo(nombre)VALUES ('	SUBPRODUCTOS	');
INSERT INTO public.tipo(nombre)VALUES ('	PECHUGAS PAVO	');
INSERT INTO public.tipo(nombre)VALUES ('	ENTERO	');
INSERT INTO public.tipo(nombre)VALUES ('	PECHUGAS POLLO	');
INSERT INTO public.tipo(nombre)VALUES ('	FILETILLOS	');
INSERT INTO public.tipo(nombre)VALUES ('	TRUTROS	');
INSERT INTO public.tipo(nombre)VALUES ('	CAMARONES	');
INSERT INTO public.tipo(nombre)VALUES ('	MARISCOS Y MOLUSCOS	');
INSERT INTO public.tipo(nombre)VALUES ('	PESCADOS	');
INSERT INTO public.tipo(nombre)VALUES ('	PESCADOS EN CONSERVA	');
INSERT INTO public.tipo(nombre)VALUES ('	BOLLERIA Y MASAS DULCES	');
INSERT INTO public.tipo(nombre)VALUES ('	CREMAS	');
INSERT INTO public.tipo(nombre)VALUES ('	HARINAS Y SEMOLA	');
INSERT INTO public.tipo(nombre)VALUES ('	HELADOS	');
INSERT INTO public.tipo(nombre)VALUES ('	INGREDIENTES REPOSTERIA	');
INSERT INTO public.tipo(nombre)VALUES ('	MERMELADAS Y DULCES	');
INSERT INTO public.tipo(nombre)VALUES ('	MANJAR Y DULCE DE LECHE	');
INSERT INTO public.tipo(nombre)VALUES ('	PANES PRE HORNEADOS	');
INSERT INTO public.tipo(nombre)VALUES ('	PANES LISTOS PARA COMER	');
INSERT INTO public.tipo(nombre)VALUES ('	POSTRES EN POLVO	');
INSERT INTO public.tipo(nombre)VALUES ('	SALSAS Y TOPPINGS	');
INSERT INTO public.tipo(nombre)VALUES ('	KETCHUP	');
INSERT INTO public.tipo(nombre)VALUES ('	MAYONESA	');
INSERT INTO public.tipo(nombre)VALUES ('	MINI PORCIONES	');
INSERT INTO public.tipo(nombre)VALUES ('	MOSTAZAS	');
INSERT INTO public.tipo(nombre)VALUES ('	SALSAS DE AJI	');
INSERT INTO public.tipo(nombre)VALUES ('	SALSAS DE SOYA	');
INSERT INTO public.tipo(nombre)VALUES ('	SALSAS DE TOMATE	');
INSERT INTO public.tipo(nombre)VALUES ('	SALSAS ESPECIALES	');
INSERT INTO public.tipo(nombre)VALUES ('	SUCEDANEOS DE LIMON	');
INSERT INTO public.tipo(nombre)VALUES ('	FRUTOS SECOS	');
INSERT INTO public.tipo(nombre)VALUES ('	DESECHABLES	');
INSERT INTO public.tipo(nombre)VALUES ('	PRODUCTOS TISSUE	');
INSERT INTO public.tipo(nombre)VALUES ('	CAFÉ GRANO ENTERO	');
INSERT INTO public.tipo(nombre)VALUES ('	CAFES SOLUBLES	');
INSERT INTO public.tipo(nombre)VALUES ('	TE Y OTRAS BEBIDAS CALIENTES	');
INSERT INTO public.tipo(nombre)VALUES ('	LECHES	');
INSERT INTO public.tipo(nombre)VALUES ('	AGUAS	');
INSERT INTO public.tipo(nombre)VALUES ('	BEBIDAS GASEOSAS	');
INSERT INTO public.tipo(nombre)VALUES ('	JUGOS	');
INSERT INTO public.tipo(nombre)VALUES ('	MAYONESAS	');
INSERT INTO public.tipo(nombre)VALUES ('	BEBIDAS VEGETALES	');
INSERT INTO public.tipo(nombre)VALUES ('	HAMBURGUESAS   	');
INSERT INTO public.tipo(nombre)VALUES ('	CARNES VEGETALES	');
INSERT INTO public.tipo(nombre)VALUES ('	QUESOS SEMI DUROS	');
INSERT INTO public.tipo(nombre)VALUES ('	HELADOS	');
INSERT INTO public.tipo(nombre)VALUES ('	MANJAR Y DULCE DE LECHE	');
INSERT INTO public.tipo(nombre)VALUES ('	ESPECIAS 	');
INSERT INTO public.tipo(nombre)VALUES ('	CALDOS	');
INSERT INTO public.tipo(nombre)VALUES ('	SEMILLAS	');
INSERT INTO public.tipo(nombre)VALUES ('	MANTEQUILLA Y MARGARINA	');
INSERT INTO public.tipo(nombre)VALUES ('	QUESOS SEMI DUROS	');

INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104521640	','	ACEITE OLIVA 5 L	','	Unidad	','	SECO	','	 $21,000 	',	1 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104512230	','	ACEITE OLIVA E/VIRGEN OLITALIA 5 L	','	Unidad	','	SECO	','	 $50,000 	',	1 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150000855	','	ACEITE OLIVA E/VIRGEN ZAYTA 5 L	','	Unidad	','	SECO	','	 $45,000 	',	1 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104514840	','	ACEITE OLIVA OLITALIA 5 L	','	Unidad	','	SECO	','	 $45,900 	',	1 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104534130	','	ACEITE SESAMO MAYAMOTO 500 ML	','	Unidad	','	SECO	','	 $3,742 	',	2 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104511950	','	ACEITE SPRAY 481 G	','	Unidad	','	SECO	','	 $5,041 	',	2 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104519410	','	ACEITE MARAVILLA 5 L	','	Unidad	','	SECO	','	 $12,000 	',	3 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150001861	','	ACEITE MARAVILLA BONANZA 900 ML	','	Unidad	','	SECO	','	 $2,583 	',	3 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104500940	','	ACEITE MARAVILLA NATURA 3 L	','	Unidad	','	SECO	','	 $10,000 	',	3 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104519250	','	ACEITE VEGETAL LOS SILOS 900 ML 	','	Unidad	','	SECO	','	 $1,658 	',	3 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104500860	','	ACEITE VEGETAL 5 L	','	Unidad	','	SECO	','	 $8,900 	',	3 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150000273	','	ACEITE FRITO MASTER 10 L	','	Unidad	','	SECO	','	 $34,000 	',	3 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104535420	','	ACEITE MARAVILLA CASALIVA 5 L 	','	Unidad	','	SECO	','	 $12,000 	',	3 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104535460	','	ACEITE PARA FREIR CASALIVA 10 L	','	Unidad	','	SECO	','	 $20,200 	',	3 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104535440	','	ACEITE VEGETAL CASALIVA 5 L	','	Unidad	','	SECO	','	 $8,900 	',	3 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104535470	','	ACEITE PARA FREIR CASALIVA 17,25 L	','	Unidad	','	SECO	','	 $36,000 	',	3 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104535430	','	ACEITE MARAVILLA CASALIVA 900 CC	','	Unidad	','	SECO	','	 $2,167 	',	3 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104535450	','	ACEITE VEGETAL CASALIVA 900 CC	','	Unidad	','	SECO	','	 $1,658 	',	3 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104512690	','	ACEITE SOYA MULTIPROPOSITO 17,25 L	','	Unidad	','	SECO	','	 $47,900 	',	3 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	101310243	','	ACETO BALSAMICO EDRA 500 CC	','	Unidad	','	SECO	','	 $1,750 	',	4 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104514870	','	ACETO BALSAMICO OLITALIA 5 L	','	Unidad	','	SECO	','	 $21,078 	',	4 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	201230620	','	VINAGRE BLANCO DON JUAN 500 ML	','	Unidad	','	SECO	','	 $592 	',	5 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150001445	','	VINAGRE BALSAMICO HERNANDEZ PLAZA 5 L	','	Unidad	','	SECO	','	 $11,200 	',	5 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150001692	','	VINAGRE BLANCO HERNANDEZ PLAZA 5 L	','	Unidad	','	SECO	','	 $3,900 	',	5 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104534090	','	VINAGRE DE MANZANA HERNANDEZ PLAZA 5 L	','	Unidad	','	SECO	','	 $5,950 	',	5 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150001883	','	VINAGRE TINTO HERNANDEZ PLAZA 5 L	','	Unidad	','	SECO	','	 $4,500 	',	5 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	201230300	','	VINAGRE VINO TINTO DON JUAN 5 L	','	Unidad	','	SECO	','	 $6,300 	',	5 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	201230700	','	VINAGRE VINO BLANCO DON JUAN 5 L	','	Unidad	','	SECO	','	 $6,900 	',	5 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	201230210	','	VINAGRE VINO TINTO DON JUAN 500 ML	','	Unidad	','	SECO	','	 $550 	',	5 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104519850	','	ACEITUNA NEGRA DESH BAJA EN SODIO 850 G	','	Unidad	','	SECO	','	 $3,490 	',	6 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	103800430	','	ACEITUNA NEGRA DESHUESADA 850 G	','	Unidad	','	SECO	','	 $3,490 	',	6 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104516010	','	ACEITUNA NEGRA RODAJA 936 G	','	Unidad	','	SECO	','	 $3,519 	',	6 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104520490	','	ACEITUNA SEVILLANA RODAJA 936 G	','	Unidad	','	SECO	','	 $3,950 	',	6 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	103800460	','	ACEITUNA SEVILLANA DESHUESADA 850 G	','	Unidad	','	SECO	','	 $3,799 	',	6 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	201221650	','	AMERICANA DON JUAN 1 KG	','	Unidad	','	SECO	','	 $3,167 	',	7 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104531630	','	PEPINILLO DILL RODAJAS HEINZ 2,9 KG	','	Unidad	','	SECO	','	 $9,817 	',	7 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104533710	','	AJI JALAPEÑO VERDE RODAJAS TOUCHE 2,9 KG	','	Unidad	','	SECO	','	 $4,500 	',	7 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104530130	','	AMERICANA TRAVERSO 1 KG	','	Unidad	','	SECO	','	 $2,167 	',	7 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104530140	','	CHUCRUT TRAVERSO 1 KG 	','	Unidad	','	SECO	','	 $2,083 	',	7 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104530240	','	PEPINILLO MEDIANO TRAVERSO 1 KG 	','	Unidad	','	SECO	','	 $3,165 	',	7 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	201210650	','	CHUCRUT DON JUAN 1 KG	','	Unidad	','	SECO	','	 $1,950 	',	7 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104535520	','	KIMCHI LA FERMENTISTA 950 g	','	Unidad	','	SECO	','	 $6,667 	',	7 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104535530	','	SAUERKRAUT ORIGINAL LA FERMENTISTA 950 G	','	Unidad	','	SECO	','	 $5,667 	',	7 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	201200060	','	PEPINO DILL 1,5 KG DON JUAN 	','	Unidad	','	SECO	','	 $5,750 	',	7 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	201200082	','	PEPINO RODAJAS CORTE LISO 4X1,5 KG 	','	Unidad	','	SECO	','	 $3,750 	',	7 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104535540	','	SAUERKRAUT PURPURA LA FERMENTISTA 950 g	','	Unidad	','	SECO	','	 $6,367 	',	7 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	201211650	','	PICKLE SURTIDO DON JUAN 1 KG	','	Unidad	','	SECO	','	 $2,250 	',	7 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104520620	','	ARROZ G2 TUCAPEL NACIONAL 2 KG	','	Unidad	','	SECO	','	 $2,798 	',	8 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104513000	','	ARROZ G2 MIRAFLORES NACIONAL 1 KG	','	Unidad	','	SECO	','	 $1,399 	',	8 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104519920	','	ARROZ G1 MIRAFLORES 1 KG	','	Unidad	','	SECO	','	 $1,599 	',	8 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150000324	','	ARROZ G1 INTEGRAL TUCAPEL 1 KG	','	Unidad	','	SECO	','	 $1,500 	',	8 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150001807	','	ARROZ G1 NACIONAL TUCAPEL 2 KG	','	Unidad	','	SECO	','	 $2,920 	',	8 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104526560	','	ARROZ PREGRANEADO TUCAPEL 1 KG	','	Unidad	','	SECO	','	 $1,510 	',	8 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104540080	','	ARROZ PREGRANEADO IMPORTADO 1 KG	','	Unidad	','	SECO	','	 $1,400 	',	8 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104529990	','	ARROZ SUSHI TUCAPEL 2 KG	','	Unidad	','	SECO	','	 $3,000 	',	8 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104535120	','	ARROZ G2 LOS GRANOS 1 kg 	','	Unidad	','	SECO	','	 $1,160 	',	8 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104537640	','	ARROZ G2 BLUE BONNET TUCAPEL 1 KG 	','	Unidad	','	SECO	','	 $1,200 	',	8 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104527320	','	ARROZ G2 MIRAFLORES IMPORTADO 1 KG	','	Unidad	','	SECO	','	 $1,520 	',	8 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104534100	','	AZUCAR RUBIA IANSA 500 G	','	Unidad	','	SECO	','	 $1,150 	',	9 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104528710	','	STEVIA LIQUIDA CERO K IANSA 250 ML	','	Unidad	','	SECO	','	 $3,124 	',	9 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104528700	','	SUCRALOSA LIQUIDA IANSA CERO K 250 ML	','	Unidad	','	SECO	','	 $2,624 	',	9 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150000893	','	AZUCAR G2 IANSA 1 KG	','	Unidad	','	SECO	','	 $1,575 	',	9 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104534660	','	AZUCAR G2 DAMA BLANCA 1 KG	','	Unidad	','	SECO	','	 $1,445 	',	9 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104537560	','	AZUCAR G2 DE REYES 25 KG	','	Saco	','	SECO	','	 $32,000 	',	9 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104537570	','	AZUCAR G2 DE REYES 1 KG	','	Unidad	','	SECO	','	 $1,400 	',	9 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104521980	','	AZUCAR G2 IANSA 5 KG	','	Saco	','	SECO	','	 $7,500 	',	9 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104532130	','	QUINOA BLANCA ZANAFOODS 1 KG (CAJA 10)	','	Unidad	','	SECO	','	 $3,613 	',	10 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104532140	','	QUINOA TRICOLOR ZANAFOODS 1 KG (CAJA 10)	','	Unidad	','	SECO	','	 $3,857 	',	10 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104527560	','	AVENA INSTANTANEA PURA AVENA 500 G	','	Unidad	','	SECO	','	 $769 	',	10 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104527550	','	AVENA INSTANTANEA PURA AVENA 900 G	','	Unidad	','	SECO	','	 $825 	',	10 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	102300260	','	NUTELLA 350 G	','	Unidad	','	SECO	','	 $4,158 	',	11 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	102310110	','	NUTELLA & GO 52 G	','	Unidad	','	SECO	','	 $1,291 	',	11 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150001829	','	CHOCMAN 33 G	','	Unidad	','	SECO	','	 $153 	',	11 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104501110	','	HUEVO GRANDE BLANCO	','	Unidad	','	FRIO	','	 $153 	',	12 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104522040	','	HUEVO EXTRA BLANCO	','	Unidad	','	FRIO	','	 $178 	',	12 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104522050	','	HUEVO MEDIANO	','	Unidad	','	FRIO	','	 $146 	',	12 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104516040	','	HUEVO EN POLVO 1 KG	','	Unidad	','	SECO	','	 $9,200 	',	12 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150000332	','	LENTEJAS BANQUETE 4 MM 1 KG	','	Unidad	','	SECO	','	 $2,200 	',	13 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150000776	','	TRIGO MOTE 1 KG	','	Unidad	','	SECO	','	 $2,500 	',	13 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104535190	','	POROTOS TORTOLA LOS GRANOS 1 kg	','	Unidad	','	SECO	','	 $3,220 	',	13 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104535160	','	POROTOS HALLADOS LOS GRANOS 1 kg	','	Unidad	','	SECO	','	 $2,240 	',	13 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104535170	','	POROTOS BLANCOS LOS GRANOS 1 kg	','	Unidad	','	SECO	','	 $2,099 	',	13 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104535150	','	LENTEJAS 6 MM LOS GRANOS 1 kg	','	Unidad	','	SECO	','	 $1,890 	',	13 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104535140	','	GARBANZO ENTERO S/PIEL LOS GRANOS 1 kg	','	Unidad	','	SECO	','	 $1,800 	',	13 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104535180	','	POROTOS NEGROS LOS GRANOS 1 kg	','	Unidad	','	SECO	','	 $1,660 	',	13 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104535130	','	ARVEJAS PARTIDAS LOS GRANOS 1kg 	','	Unidad	','	SECO	','	 $1,260 	',	13 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104527240	','	LENTEJAS BANQUETE 6 MM 1 KG	','	Unidad	','	SECO	','	 $2,300 	',	13 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150001784	','	MERMELADA MORA PERELLO 250 G	','	Unidad	','	SECO	','	 $608 	',	14 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150001530	','	MIEL DE PALMA COCALAN 700 G	','	Unidad	','	SECO	','	 $8,750 	',	14 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104524370	','	MERMELADA FRUTILLA PERELLO 250 G	','	Unidad	','	SECO	','	 $608 	',	14 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150001782	','	MERMELADA DAMASCO PERELLO 250 G	','	Unidad	','	SECO	','	 $608 	',	14 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150001783	','	MERMELADA DURAZNO PERELLO 250 G	','	Unidad	','	SECO	','	 $608 	',	14 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104530200	','	AZUCAR MINI 5 G	','	Unidad	','	SECO	','	 $12 	',	15 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104501190	','	SUCRALOSA MINI LAVAZZA 0,5 G	','	Unidad	','	SECO	','	 $9 	',	15 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104500810	','	SUCRALOSA MINI ICB 0,5 G	','	Unidad	','	SECO	','	 $9 	',	15 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104522200	','	SUCRALOSA MINI IANSA 0,5 G	','	Unidad	','	SECO	','	 $9 	',	15 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104522210	','	SUCRALOSA MINI RELKON 0,5 G	','	Unidad	','	SECO	','	 $9 	',	15 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104501230	','	AZUCAR MINI ICB 5 G	','	Unidad	','	SECO	','	 $14 	',	15 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104501170	','	AZUCAR MINI LAVAZZA 5 G	','	Unidad	','	SECO	','	 $14 	',	15 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104521200	','	AZUCAR MINI IANSA 5 G	','	Unidad	','	SECO	','	 $14 	',	15 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104522090	','	MANJAR MINI COLUN 20 G	','	Unidad	','	SECO	','	 $98 	',	15 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104535210	','	MERMELADA MINI DAMASCO RELKON 20 G	','	Unidad	','	SECO	','	 $56 	',	15 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104535220	','	MERMELADA MINI DURAZNO RELKON 20 G	','	Unidad	','	SECO	','	 $56 	',	15 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104535230	','	MERMELADA MINI FRUTILLA LIGHT RELKO 20 G	','	Unidad	','	SECO	','	 $83 	',	15 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104535240	','	MERMELADA MINI FRUTILLA RELKON 20 G	','	Unidad	','	SECO	','	 $56 	',	15 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104535250	','	MERMELADA MINI MORA RELKON 20 G	','	Unidad	','	SECO	','	 $56 	',	15 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104535260	','	MIEL MINI RELKON 20 G	','	Unidad	','	SECO	','	 $143 	',	15 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104522190	','	SAL MINI PORCION RELKON 1 G	','	Unidad	','	SECO	','	 $3 	',	15 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104501150	','	AZUCAR RUBIA MINI ICB 5 G	','	Unidad	','	SECO	','	 $14 	',	15 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150000158	','	PURE DE PAPAS EN ESCAMAS KNORR 2 KG	','	Unidad	','	SECO	','	 $15,380 	',	16 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150001765	','	CARNE VEGETAL 500 G	','	Unidad	','	SECO	','	 $1,650 	',	16 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150001863	','	CHUCHOCA 1 KG	','	Unidad	','	SECO	','	 $2,000 	',	16 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104534150	','	JENGIBRE ROSADO MAYAMOTO 1 KG	','	Unidad	','	SECO	','	 $3,160 	',	16 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104534180	','	WASABI EN POLVO MAYAMOTO 1 KG	','	Unidad	','	SECO	','	 $7,000 	',	16 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150001112	','	COUS COUS DIVELLA 500 G	','	Unidad	','	SECO	','	 $1,817 	',	16 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150001768	','	COUS COUS CAROZZI 250 G	','	Unidad	','	SECO	','	 $1,380 	',	16 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150000883	','	POLENTA DIVELLA 500 G	','	Unidad	','	SECO	','	 $1,919 	',	16 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150000003	','	PURE DE PAPAS MACROFOOD 1 KG	','	Unidad	','	SECO	','	 $4,099 	',	16 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104524830	','	POLENTA 250 G	','	Unidad	','	SECO	','	 $642 	',	16 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104538060	','	PANKO BLANCO MAYAMOTO 1 KG	','	Unidad	','	SECO	','	 $2,600 	',	16 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104530320	','	HARINA TEMPURA 1 KG	','	Unidad	','	SECO	','	 $3,200 	',	16 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104525460	','	PURE DE PAPA INSTANTANEO 1 KG	','	Unidad	','	SECO	','	 $4,317 	',	16 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150001309	','	FETUCCINI 88 CAROZZI 400 G	','	Unidad	','	SECO	','	 $972 	',	17 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	102200082	','	ESPIRALES DON VITTORIO 400 G NV	','	Unidad	','	SECO	','	 $683 	',	17 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	102200085	','	RIGATONE DON VITTORIO 400 G NV	','	Unidad	','	SECO	','	 $683 	',	17 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	102200081	','	CORBATA GRANDE DON VITTORIO 400 G NV	','	Unidad	','	SECO	','	 $683 	',	17 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104528880	','	LASAÑA PRECOCIDA LUCCHETTI 360 G	','	Unidad	','	SECO	','	 $1,271 	',	17 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104528420	','	CABELLOS DE ANGEL CORTO LUCCHETTI 400 G	','	Unidad	','	SECO	','	 $720 	',	17 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104528350	','	ESPIRALES ITALIANISSIMO 5 KG	','	Unidad	','	SECO	','	 $7,800 	',	17 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104528360	','	MOSTACHOLI ITALIANISSIMO 5 KG	','	Unidad	','	SECO	','	 $7,800 	',	17 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104528370	','	QUIFARO ITALIANISSIMO 5 KG	','	Unidad	','	SECO	','	 $7,800 	',	17 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104528380	','	CORBATAS ITALIANISSIMO 5 KG	','	Unidad	','	SECO	','	 $7,800 	',	17 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104528390	','	SPAGHETTI N°5 ITALIANISSIMO 5 KG	','	Unidad	','	SECO	','	 $7,800 	',	17 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104528400	','	TALLARIN N°77 ITALIANISSIMO 5 KG	','	Unidad	','	SECO	','	 $7,800 	',	17 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150001831	','	FIDEOS GRANIZO CAROZZI 250 G	','	Unidad	','	SECO	','	 $700 	',	17 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150001770	','	RAVIOLES DE CARNE CAROZZI 400 G	','	Unidad	','	SECO	','	 $1,690 	',	17 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104526960	','	MOSTACHOLI LUCCHETTI 400 G	','	Unidad	','	SECO	','	 $720 	',	17 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104526970	','	QUIFAROS LUCCHETTI 400 G	','	Unidad	','	SECO	','	 $720 	',	17 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104526980	','	CORBATAS LUCCHETTI 400 G	','	Unidad	','	SECO	','	 $720 	',	17 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104526990	','	CARACOLES LUCCHETTI 400 G	','	Unidad	','	SECO	','	 $720 	',	17 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104527000	','	CANUTO LUCCHETTI 400 G	','	Unidad	','	SECO	','	 $720 	',	17 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104527010	','	RIGATTI LUCCHETTI 400 G	','	Unidad	','	SECO	','	 $720 	',	17 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104527020	','	ESPIRALES LUCCHETTI 400 G	','	Unidad	','	SECO	','	 $720 	',	17 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104527030	','	CORBATITAS LUCCHETTI 400 G	','	Unidad	','	SECO	','	 $720 	',	17 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104527040	','	TALLARIN N°78 LUCCHETTI 400 G	','	Unidad	','	SECO	','	 $760 	',	17 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104527050	','	SPAGHETTI N°5 LUCCHETTI 400 G	','	Unidad	','	SECO	','	 $760 	',	17 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104538900	','	RAVIOLI CARNE CAROZZI 1 KG 	','	Unidad	','	SECO	','	 $4,200 	',	17 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104527060	','	TALLARIN N°77 LUCCHETTI 400 G	','	Unidad	','	SECO	','	 $760 	',	17 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150000368	','	CREMA CHAMPIÑON MACROFOOD 1 KG	','	Unidad	','	SECO	','	 $2,250 	',	18 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150000370	','	CREMA TOMATE MACROFOOD 1 KG	','	Unidad	','	SECO	','	 $2,250 	',	18 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150000369	','	CREMA ESPARRAGOS MACROFOOD 1 KG	','	Unidad	','	SECO	','	 $1,848 	',	18 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150001186	','	CREMA CHOCLO MACROFOOD 1 KG	','	Unidad	','	SECO	','	 $1,815 	',	18 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150000578	','	SAL DE MAR GOURMET LOBOS 800 G	','	Unidad	','	SECO	','	 $1,483 	',	19 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150000579	','	SAL FINA LOBOS 1 KG	','	Unidad	','	SECO	','	 $636 	',	19 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104526090	','	SAL FINA 1 KG	','	Unidad	','	SECO	','	 $490 	',	19 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104528530	','	HELADO CHOCOLATE BRESLER 2,4 L	','	Unidad	','	CONGELADOS	','	 $4,625 	',	20 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104528540	','	HELADO VAINILLA BRESLER 2,4 L	','	Unidad	','	CONGELADOS	','	 $4,725 	',	20 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104528550	','	HELADO TRISABOR BRESLER 2,4 L	','	Unidad	','	CONGELADOS	','	 $5,000 	',	20 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104528560	','	HELADO PIÑA BRESLER 2,4 L	','	Unidad	','	CONGELADOS	','	 $4,625 	',	20 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104529100	','	TORTILLAS ZANAFOODS 18 CM 12 UDS.	','	Unidad	','	SECO	','	 $1,169 	',	21 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104529110	','	TORTILLAS ZANAFOODS 23 CM 12 UDS.	','	Unidad	','	SECO	','	 $2,110 	',	21 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104512160	','	TORTILLAS PANCHO VILLA 28 CM 12 UDS. 	','	Unidad	','	SECO	','	 $2,599 	',	21 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104529120	','	TORTILLAS ZANAFOODS 28 CM 12 UDS.	','	Unidad	','	SECO	','	 $2,599 	',	21 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104303010	','	PAPA 14 MM AVIKO 2,5 KG	','	Unidad	','	CONGELADOS	','	 $5,825 	',	22 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104529210	','	PAPA PREMIUM CRUNCH 10 MM AVIKO 2,27 KG	','	Unidad	','	CONGELADOS	','	 $6,375 	',	22 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104516720	','	PAPA SUPERLONG C/PIEL 10 MM AVIKO 2,5 KG	','	Unidad	','	CONGELADOS	','	 $5,725 	',	22 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104330230	','	PAPA 7 MM AVIKO 2,5 KG	','	Unidad	','	CONGELADOS	','	 $6,100 	',	22 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104330270	','	PAPA CRUNCH 10 MM AVIKO 2,5 KG	','	Unidad	','	CONGELADOS	','	 $6,700 	',	22 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104527520	','	PAPA 10 MM AVIKO 2,5 KG	','	Unidad	','	CONGELADOS	','	 $5,450 	',	22 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104527430	','	PAPA 12 MM AVIKO 2,5 KG	','	Unidad	','	CONGELADOS	','	 $5,550 	',	22 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104517930	','	PAPA CRINKLE 12 MM AVIKO 2,5 KG	','	Unidad	','	CONGELADOS	','	 $5,500 	',	22 	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104300450	','	FRUTILLA IQF 2,5 KG	','	Unidad	','	CONGELADOS	','	 $10,000 	',	23	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104524690	','	PULPA MARACUYA S/SEMILLAS S/AZUCAR 1 KG	','	Unidad	','	CONGELADOS	','	 $5,750 	',	23	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104300050	','	ARANDANOS IQF 2 KG	','	Unidad	','	CONGELADOS	','	 $10,000 	',	23	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104519590	','	ESPINACA A LA CREMA IQF ARDO 2,5 KG	','	Unidad	','	CONGELADOS	','	 $5,075 	',	24	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104520730	','	HAMBURGUESA VEGETARIANA ARDO 1,2 KG 75 G	','	Unidad	','	CONGELADOS	','	 $8,167 	',	24	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104303640	','	PASTA CHOCLO MINUTO VERDE 1 KG	','	Unidad	','	CONGELADOS	','	 $2,571 	',	24	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104518960	','	PULPA JUGO MELON C/AZUCAR 1 KG	','	Unidad	','	CONGELADOS	','	 $3,550 	',	25	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104518910	','	PULPA JUGO FRUTILLA C/AZUCAR 1 KG	','	Unidad	','	CONGELADOS	','	 $3,300 	',	25	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104310440	','	PULPA JUGO PIÑA 1 KG	','	Unidad	','	CONGELADOS	','	 $4,100 	',	25	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104303300	','	PULPA JUGO FRAMBUESA 1 KG	','	Unidad	','	CONGELADOS	','	 $6,000 	',	25	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104519510	','	PULPA JUGO LIMON S/AZUCAR 1 KG	','	Unidad	','	CONGELADOS	','	 $3,920 	',	25	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104518970	','	PULPA JUGO MANGO C/AZUCAR 1 KG	','	Unidad	','	CONGELADOS	','	 $4,100 	',	25	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104519110	','	PULPA JUGO FRAMBUESA S/AZUCAR 1 KG	','	Unidad	','	CONGELADOS	','	 $6,200 	',	25	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104519120	','	PULPA JUGO MANGO S/AZUCAR 1 KG	','	Unidad	','	CONGELADOS	','	 $4,400 	',	25	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104518950	','	PULPA JUGO CHIRIMOYA C/AZUCAR 1 KG	','	Unidad	','	CONGELADOS	','	 $5,400 	',	25	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104300530	','	PRIMAVERA VERDURAS IQF ARDO 2,5 KG	','	Unidad	','	CONGELADOS	','	 $4,925 	',	26	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104321040	','	PRIMAVERA PREMIUM IQF ARDO 1 KG	','	Unidad	','	CONGELADOS	','	 $2,110 	',	26	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104525040	','	MIX BERRIES 1 KG	','	Unidad	','	CONGELADOS	','	 $6,600 	',	27	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104529220	','	CHOCLO EN TROZOS FDM 2 KG	','	Unidad	','	CONGELADOS	','	 $7,333 	',	27	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104519740	','	CEBOLLA RODAJAS IQF ARDO 2,5 KG	','	Unidad	','	CONGELADOS	','	 $6,500 	',	27	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104521770	','	CHOCLO GRANO IQF ARDO 2,5 KG	','	Unidad	','	CONGELADOS	','	 $6,500 	',	27	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104519610	','	PIMENTON VERDE JULIANAS IQF ARDO 2,5 KG	','	Unidad	','	CONGELADOS	','	 $5,250 	',	27	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104519600	','	PIMENTON ROJO JULIANAS IQF ARDO 2,5 KG	','	Unidad	','	CONGELADOS	','	 $6,425 	',	27	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104515110	','	POROTO VERDE C/FRANC IQF ARDO 2,5 KG	','	Unidad	','	CONGELADOS	','	 $6,500 	',	27	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104321070	','	CHAMPIÑON LAMINADO IQF ARDO 2,5 KG	','	Unidad	','	CONGELADOS	','	 $6,600 	',	27	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104519710	','	FONDOS DE ALCACHOFAS IQF ARDO 2,5 KG	','	Unidad	','	CONGELADOS	','	 $13,500 	',	27	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104519750	','	CEBOLLA CUBOS IQF ARDO 2,5 KG	','	Unidad	','	CONGELADOS	','	 $6,500 	',	27	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104301050	','	ARVEJAS IQF ARDO  2,5 KG	','	Unidad	','	CONGELADOS	','	 $5,825 	',	27	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104300500	','	COLIFLOR IQF ARDO 2,5 KG	','	Unidad	','	CONGELADOS	','	 $5,100 	',	27	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104519580	','	ESPINACA IQF ARDO 2,5 KG	','	Unidad	','	CONGELADOS	','	 $5,025 	',	27	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104520710	','	BROCOLI ARDO 1 KG	','	Unidad	','	CONGELADOS	','	 $2,983 	',	27	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150002096	','	POROTO GRANADO 2 KG	','	Unidad	','	CONGELADOS	','	 $9,000 	',	27	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104519650	','	CHOCLO GRANO IQF ARDO 1 KG	','	Unidad	','	CONGELADOS	','	 $2,800 	',	27	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104520700	','	POROTO VERDE CORTE FRANCES ARDO 1 KG	','	Unidad	','	CONGELADOS	','	 $2,010 	',	27	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104519690	','	ARVEJAS IQF ARDO 1 KG	','	Unidad	','	CONGELADOS	','	 $2,120 	',	27	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104519700	','	HABAS FINAS IQF ARDO 1 KG	','	Unidad	','	CONGELADOS	','	 $2,950 	',	27	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104534220	','	JAMON SERRANO LAMINADO J.LLORENS 500 g	','	Unidad	','	FRIO	','	 $10,990 	',	27	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104525830	','	TOCINO AHUMADO PREFERIDA CORTADO 500 G	','	Unidad	','	FRIO	','	 $5,725 	',	28	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	105045500	','	TOCINO AHUMADO LAM CONG NACIONAL 1 KG	','	Unidad	','	CONGELADOS	','	 $9,990 	',	28	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104534620	','	TOCINO LAMINADO SUGARDALE 1 kg	','	Unidad	','	CONGELADOS	','	 $10,490 	',	28	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104534500	','	PEPPERONI ULTRADELGADO SUGARDALE 1 KG 	','	Unidad	','	CONGELADOS	','	 $9,090 	',	28	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104521840	','	TOCINO LAMINADO SUGARDALE 6,8 KG	','	Unidad	','	CONGELADOS	','	 $69,972 	',	28	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104520080	','	COCTEL DE FRUTA NACIONAL 3 KG	','	Unidad	','	SECO	','	 $9,000 	',	29	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104520060	','	DURAZNO MITADES 3 KG	','	Unidad	','	SECO	','	 $8,833 	',	29	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104520070	','	DURAZNO TROCITOS 3 KG	','	Unidad	','	SECO	','	 $8,667 	',	29	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104523990	','	FRUTA LISTA DURAZNO C/JUGO DE UVA 113 G	','	Unidad	','	SECO	','	 $354 	',	29	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104510130	','	FRUTA LISTA DURAZNO C/SUCRALOSA 113 G	','	Unidad	','	SECO	','	 $354 	',	29	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	101530550	','	PIÑA EN RODAJAS ESMERALDA 3 KG	','	Unidad	','	SECO	','	 $8,317 	',	29	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	101530450	','	PIÑA EN RODAJAS ESMERALDA 567 G	','	Unidad	','	SECO	','	 $1,625 	',	29	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150001898	','	CEREZAS AL JUGO CON CAROZO 580 G	','	Unidad	','	SECO	','	 $1,917 	',	29	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150000270	','	DURAZNO MITADES REGIMEL 560 G	','	Unidad	','	SECO	','	 $2,000 	',	29	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	150001031	','	MARRASQUINO ROJO 1,1 KG	','	Unidad	','	SECO	','	 $6,167 	',	29	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	101530600	','	PIÑA EN TROCITOS ESMERALDA 3 KG	','	Unidad	','	SECO	','	 $8,000 	',	29	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104526280	','	FRUTA LISTA TUTTI FRUTI C/JUGO UVA 113 G	','	Unidad	','	SECO	','	 $354 	',	29	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	101530700	','	PIÑA EN TROCITOS ESMERALDA 565 G	','	Unidad	','	SECO	','	 $1,538 	',	29	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104524750	','	PIMENTON ENTERO ESMERALDA 780 G	','	Unidad	','	SECO	','	 $2,166 	',	30	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	101500120	','	CHAMPIÑON LAMINADO ESMERALDA 2,84 KG	','	Unidad	','	SECO	','	 $7,583 	',	30	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104533700	','	FONDOS DE ALCACHOFAS EXCELENCIA 907 G 	','	Unidad	','	SECO	','	 $4,333 	',	30	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	101500200	','	CHAMPIÑONES ENTEROS ESMERALDA 184 G	','	Unidad	','	SECO	','	 $575 	',	30	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104534690	','	CHAMPIÑON LAMINADO ZANAFOODS 400 G	','	Unidad	','	SECO	','	 $875 	',	30	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	101541090	','	CORAZONES DE ALCACHOFA ESMERALDA 400 G	','	Unidad	','	SECO	','	 $1,960 	',	30	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104320510	','	ESPARRAGOS VERDES ESMERALDA 425 G	','	Unidad	','	SECO	','	 $1,791 	',	30	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	101520120	','	PALMITOS ESMERALDA 400 G	','	Unidad	','	SECO	','	 $2,000 	',	30	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	101520140	','	PALMITOS ESMERALDA 810 G	','	Unidad	','	SECO	','	 $3,300 	',	30	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	101520200	','	PALMITOS RODAJAS ESMERALDA 400 G	','	Unidad	','	SECO	','	 $1,542 	',	30	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	101520250	','	PALMITOS RODAJAS ESMERALDA 810 G	','	Unidad	','	SECO	','	 $2,600 	',	30	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	101510000	','	PIMENTON ENTERO ESMERALDA 2,9 KG	','	Unidad	','	SECO	','	 $6,100 	',	30	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	101510040	','	PIMENTON TIRAS ROJAS ESMERALDA 2,9 KG	','	Unidad	','	SECO	','	 $5,671 	',	30	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	104535200	','	CHOCLITOS COCKTAIL ZANAFOODS 425 G 	','	Unidad	','	SECO	','	 $1,232 	',	30	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	108004000	','	TOMATE ITALIANO CUBO GALON 2,50 KG	','	Unidad	','	SECO	','	 $5,817 	',	30	);
INSERT INTO public.insumo(codigo,descripcion,descripcion_umv,temperatura,precio_unidad,tipo_id)VALUES ('	108004050	','	TOMATE ITALIANO ENTERO PEL GALON 2,55 KG	','	Unidad	','	SECO	','	 $6,000 	',	30	);




INSERT INTO public.stock(cantidad,stock_critico,stock_inicial,insumos_id)VALUES (1000,1000,8,1);
INSERT INTO public.stock(cantidad,stock_critico,stock_inicial,insumos_id)VALUES (2500,2600,9,2);
INSERT INTO public.stock(cantidad,stock_critico,stock_inicial,insumos_id)VALUES (3000,1000,3,3);
INSERT INTO public.stock(cantidad,stock_critico,stock_inicial,insumos_id)VALUES (50,10,8,4);


INSERT INTO public.preparacion(stock_necesario, tiempo_preparacion, insumo_id, plato_id, usuario_id)	VALUES (200, 20, 49, 1,1);
INSERT INTO public.preparacion(stock_necesario, tiempo_preparacion, insumo_id, plato_id, usuario_id)	VALUES (200, 10, 66, 1,1);

INSERT INTO public.preparacion(stock_necesario, tiempo_preparacion, insumo_id, plato_id, usuario_id)	VALUES (200, 10, 50, 2,1);
INSERT INTO public.preparacion(stock_necesario, tiempo_preparacion, insumo_id, plato_id, usuario_id)	VALUES (200, 10, 80, 2,1);

